version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app_main:
    build:
      context: ./main
      dockerfile: Dockerfile
    restart: always
    depends_on:
      redis:
          condition: service_healthy
    stdin_open: true
    tty: true

  app_worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
      - app_main
    tty: true
